#include <iostream>
#include "single-switch.h"

SingleSwitch switches[40] = {
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "3.3V Power", 1),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "5V Power", 2),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 2 (SDA1)", 3),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "5V Power", 4),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 3 (SCL1)", 5),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 6),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 4", 7),
    SingleSwitch(true, DefaultValue::HIGH, "GPIO 14 (TXD0)", 8),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 9),
    SingleSwitch(true, DefaultValue::HIGH, "GPIO 15 (RXD0)", 10),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 17", 11),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 18 (PCM_CLK)", 12),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 27", 13),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 14),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 22", 15),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 23", 16),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "3.3V Power", 17),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 24", 18),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 10 (MOSI)", 19),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 20),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 9 (MISO)", 21),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 25", 22),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 11 (SCLK)", 23),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 8 (CE0)", 24),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 25),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 7 (CE1)", 26),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 0 (ID_SD)", 27),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 1 (ID_SC)", 28),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 5", 29),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 30),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 6", 31),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 12 (PWM0)", 32),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 13 (PWM1)", 33),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 34),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 19 (PCM_FS)", 35),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 16", 36),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 26", 37),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 20 (PCM_DIN)", 38),
    SingleSwitch(false, DefaultValue::NOT_CONFIGURABLE, "Ground", 39),
    SingleSwitch(true, DefaultValue::LOW, "GPIO 21 (PCM_DOUT)", 40)};